kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: arm

workspace:
  base: /home/builder/package
  path: ''

steps:

- name: download public key
  image: plugins/download
  settings:
    source: https://alpine-pkgs.ikaruswill.com/ikaruswill.rsa.pub
    sha256: ff2ac6f6d1f0a53c7d6b661147f8e8d13ed5b3ca0ffe2c7b2e870c5178107719

- name: build
  image: ikaruswill/alpine-abuild:3.9
  environment:
    RSA_PRIVATE_KEY:
      from_secret: ikaruswill_private_key
    RSA_PRIVATE_KEY_NAME: ikaruswill.rsa
  volumes:
  - name: packages
    path: /packages


- name: test
  image: alpine:3.9
  commands:
  - cp ikaruswill.rsa.pub /etc/apk/keys/
  - apk -U add --no-progress --upgrade /packages/builder/armv7/*.apk
  volumes:
  - name: packages
    path: /packages

- name: deploy
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - /packages/builder/armv7/*
    - /packages/*
    checksum:
    - sha512
  volumes:
  - name: packages
    path: /packages
  when:
    event:
    - tag

trigger:
  branch:
  - master

volumes:
- name: packages
  temp: {}
