kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: arm

clone:
  depth: 1

steps:
- name: download public key
  image: plugins/download
  settings:
    source: https://alpine-pkgs.ikaruswill.com/ikaruswill-alpine-pkgs.pub
    sha256: 37480e5fba2927c21b36a04ffc296f44b813f3207bb2ad7eec9dd96c0439478c

- name: build
  image: ikaruswill/alpine-abuild:v10
  environment:
    RSA_PRIVATE_KEY:
      from_secret: ikaruswill_alpine_pkgs_private_key
    RSA_PRIVATE_KEY_NAME: ikaruswill-alpine-pkgs
    REPODEST: /drone/src/packages
  commands:
  - cp * /home/builder/package/
  - cd /home/builder/package
  - abuilder -r
  volumes:
  - name: builder
    path: /home/builder/package

- name: test
  image: alpine:3.10
  commands:
  - cp ikaruswill-alpine-pkgs.pub /etc/apk/keys/
  - apk -U add --no-progress --upgrade packages/builder/armv7/*.apk

- name: deploy
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_release_public_token
    files:
    - packages/builder/armv7/*
    checksum:
    - sha512
  when:
    ref:
    - refs/tags/*

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

volumes:
- name: builder
  temp: {}

---
kind: secret
name: docker_username
get:
  path: drone-secrets
  name: docker_username
---
kind: secret
name: docker_password
get:
  path: drone-secrets
  name: docker_password
---
kind: secret
name: github_release_public_token
get:
  path: drone-secrets
  name: github_release_public_token
---
kind: secret
name: ikaruswill_alpine_pkgs_private_key
get:
  path: drone-secrets
  name: ikaruswill_alpine_pkgs_private_key